### ISSUE TITLE
Fix up Interweave issues

### ISSUE THREAD

**Issue by rmccue** [humanmade/h2#233]
These need to be fixed before we can turn on Interweave by default.

Noting these down as I find them:

* [x] srcset/sizes not supported on images: https://github.com/milesj/interweave/issues/49
* [x] Embeds (inc. WordPress oEmbed) not supported/rendered (likely need to support iframes?): https://github.com/milesj/interweave/issues/50
    * https://updates.hmn.md/2018/07/12/my-360-feedback/
    * https://updates.hmn.md/2018/06/01/weekly-update-9-48/#comment-20220
    * Instagram: https://updates.hmn.md/2018/08/03/weekly-update-9-57/#comment-20885
* [x] Videos are wrong size: https://updates.hmn.md/2018/08/03/weekly-update-9-57/#comment-20887
* [x] Weird trailing list item on https://growth.hmn.md/2018/06/12/growth-call-54/
* [x] Video broken on https://dfl.hmn.md/2018/10/16/iphone-app/
* [ ] `start` isn't supported on `ol`: https://github.com/milesj/interweave/issues/76
